// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220324211254_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Level1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Level1");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Name = "Assets"
                        },
                        new
                        {
                            Id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Name = "Liability"
                        },
                        new
                        {
                            Id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Name = "Equity"
                        },
                        new
                        {
                            Id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Name = "Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Level2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid>("Level1_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Level1_id");

                    b.ToTable("Level2");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Non - Current Assets"
                        },
                        new
                        {
                            Id = new Guid("12000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Current Assets"
                        },
                        new
                        {
                            Id = new Guid("21000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Non - Current Liabilities"
                        },
                        new
                        {
                            Id = new Guid("22000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Current Liabilities"
                        },
                        new
                        {
                            Id = new Guid("31000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Owner's Equity"
                        },
                        new
                        {
                            Id = new Guid("41000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Income"
                        },
                        new
                        {
                            Id = new Guid("51000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Cost of Revenue (COGS)"
                        },
                        new
                        {
                            Id = new Guid("52000000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "General & Administrative Expenses"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Level3", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid>("Level2_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Level2_id");

                    b.ToTable("Level3");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("11000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Fixed Assets"
                        },
                        new
                        {
                            Id = new Guid("11200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("11000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Intangible Assets"
                        },
                        new
                        {
                            Id = new Guid("11300000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("11000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Financial Assets"
                        },
                        new
                        {
                            Id = new Guid("11400000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("11000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Leased Assets"
                        },
                        new
                        {
                            Id = new Guid("12100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("12000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Cash & Cash Equivalents"
                        },
                        new
                        {
                            Id = new Guid("12200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("12000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accounts Receivable"
                        },
                        new
                        {
                            Id = new Guid("12300000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("12000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Prepayments, Advances, deposits"
                        },
                        new
                        {
                            Id = new Guid("12400000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("12000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Inventory / Merchandise"
                        },
                        new
                        {
                            Id = new Guid("21100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("21000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Long - term Borrowings"
                        },
                        new
                        {
                            Id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("22000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accounts Payable"
                        },
                        new
                        {
                            Id = new Guid("22200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("22000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Other Liability"
                        },
                        new
                        {
                            Id = new Guid("31100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("31000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Share Capital"
                        },
                        new
                        {
                            Id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("31000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Reserves"
                        },
                        new
                        {
                            Id = new Guid("41100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("41000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Operating Income"
                        },
                        new
                        {
                            Id = new Guid("41200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("41000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Non - Operating Income"
                        },
                        new
                        {
                            Id = new Guid("41300000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("41000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Discount"
                        },
                        new
                        {
                            Id = new Guid("51100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("51000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Direct Cost"
                        },
                        new
                        {
                            Id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("52000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Administrative Expenses"
                        },
                        new
                        {
                            Id = new Guid("52200000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level2_id = new Guid("52000000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Selling, Promotions & Advertising"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Level4", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid>("Level1_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Level3_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Level1_id");

                    b.HasIndex("Level3_id");

                    b.ToTable("Level4");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Land"
                        },
                        new
                        {
                            Id = new Guid("11120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Buildings"
                        },
                        new
                        {
                            Id = new Guid("11130000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = new Guid("11140000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accumulated Depreciation - Buildings (Contra Asset)"
                        },
                        new
                        {
                            Id = new Guid("11410000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Leased Building"
                        },
                        new
                        {
                            Id = new Guid("11420000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Leased Equipment"
                        },
                        new
                        {
                            Id = new Guid("11430000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accumulated Depreciation - Leased Building (Contra Asset)"
                        },
                        new
                        {
                            Id = new Guid("11440000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("11400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accumulated Depreciation - Leased Equipment (Contra Asset)"
                        },
                        new
                        {
                            Id = new Guid("12110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Bank"
                        },
                        new
                        {
                            Id = new Guid("12120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("12210000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Trade Receivable"
                        },
                        new
                        {
                            Id = new Guid("12220000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Other Receivable"
                        },
                        new
                        {
                            Id = new Guid("12310000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12300000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Sales Tax Asset"
                        },
                        new
                        {
                            Id = new Guid("12320000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12300000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Income Tax Asset"
                        },
                        new
                        {
                            Id = new Guid("12410000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Raw Material"
                        },
                        new
                        {
                            Id = new Guid("12420000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Work in Progress"
                        },
                        new
                        {
                            Id = new Guid("12430000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Finished Goods"
                        },
                        new
                        {
                            Id = new Guid("12440000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("10000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("12400000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Goods in Transition"
                        },
                        new
                        {
                            Id = new Guid("21110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("21100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Long - Term Loans"
                        },
                        new
                        {
                            Id = new Guid("21120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("21100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Lease Liability"
                        },
                        new
                        {
                            Id = new Guid("22110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Bank Over draft"
                        },
                        new
                        {
                            Id = new Guid("22120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Trade Accounts Payable"
                        },
                        new
                        {
                            Id = new Guid("22130000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Accrued Expenses, Loan & Other Payable"
                        },
                        new
                        {
                            Id = new Guid("22140000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Short Term Lease Payable"
                        },
                        new
                        {
                            Id = new Guid("22150000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Sales Tax Liability"
                        },
                        new
                        {
                            Id = new Guid("22160000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Income Tax Liability"
                        },
                        new
                        {
                            Id = new Guid("22210000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("20000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("22200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Unearned Revenue"
                        },
                        new
                        {
                            Id = new Guid("31110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Paid up Share Capital"
                        },
                        new
                        {
                            Id = new Guid("31210000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Share Premium"
                        },
                        new
                        {
                            Id = new Guid("31220000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Suplus /Defecit/ Retained Earnings"
                        },
                        new
                        {
                            Id = new Guid("31230000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Revaluation Reserve"
                        },
                        new
                        {
                            Id = new Guid("31240000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Exchange Differences"
                        },
                        new
                        {
                            Id = new Guid("31250000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Drawings"
                        },
                        new
                        {
                            Id = new Guid("31260000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("30000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("31200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Opening Balance equity"
                        },
                        new
                        {
                            Id = new Guid("41110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("41100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Revenue"
                        },
                        new
                        {
                            Id = new Guid("41210000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("41200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Interest Income"
                        },
                        new
                        {
                            Id = new Guid("41220000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("41200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Gain/Loss on Sale of Assets"
                        },
                        new
                        {
                            Id = new Guid("41310000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("40000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("41300000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Discount"
                        },
                        new
                        {
                            Id = new Guid("51110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("51100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Direct Labor / Salaries"
                        },
                        new
                        {
                            Id = new Guid("51120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("51100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Direct Material"
                        },
                        new
                        {
                            Id = new Guid("51130000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("51100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Depreciation Expense"
                        },
                        new
                        {
                            Id = new Guid("51140000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("51100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Cost Of Goods Sold"
                        },
                        new
                        {
                            Id = new Guid("52110000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Salaries Expense"
                        },
                        new
                        {
                            Id = new Guid("52120000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Wages Expense"
                        },
                        new
                        {
                            Id = new Guid("52130000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Utilities Expense"
                        },
                        new
                        {
                            Id = new Guid("52140000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Entertainment / Meals Expense"
                        },
                        new
                        {
                            Id = new Guid("52150000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Printing & Stationary Expense"
                        },
                        new
                        {
                            Id = new Guid("52160000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Rent Expense"
                        },
                        new
                        {
                            Id = new Guid("52170000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Office Expense"
                        },
                        new
                        {
                            Id = new Guid("52180000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Repair & Maintenance Expense"
                        },
                        new
                        {
                            Id = new Guid("52190000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Transportation & Conveyance Expense"
                        },
                        new
                        {
                            Id = new Guid("52101000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Interest Expense"
                        },
                        new
                        {
                            Id = new Guid("52101100-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52100000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Tax Expense"
                        },
                        new
                        {
                            Id = new Guid("52210000-5566-7788-99aa-bbccddeeff00"),
                            IsDelete = false,
                            Level1_id = new Guid("50000000-5566-7788-99aa-bbccddeeff00"),
                            Level3_id = new Guid("52200000-5566-7788-99aa-bbccddeeff00"),
                            Name = "Advertising / Marketing Expense"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FiscalYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("GSTRegistrationNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IncomeTaxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LegalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            Name = "SBBU"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WorkFlowStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkFlowStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDelete = false,
                            State = 0,
                            Status = "Draft",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDelete = false,
                            State = 1,
                            Status = "Rejected",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            IsDelete = false,
                            State = 2,
                            Status = "Unpaid",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            IsDelete = false,
                            State = 3,
                            Status = "Partial Paid",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            IsDelete = false,
                            State = 4,
                            Status = "Paid",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            IsDelete = false,
                            State = 5,
                            Status = "Submitted",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            IsDelete = false,
                            State = 7,
                            Status = "Cancelled",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Level2", b =>
                {
                    b.HasOne("Domain.Entities.Level1", "Level1")
                        .WithMany("Level2")
                        .HasForeignKey("Level1_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level1");
                });

            modelBuilder.Entity("Domain.Entities.Level3", b =>
                {
                    b.HasOne("Domain.Entities.Level2", "Level2")
                        .WithMany("Level3")
                        .HasForeignKey("Level2_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level2");
                });

            modelBuilder.Entity("Domain.Entities.Level4", b =>
                {
                    b.HasOne("Domain.Entities.Level1", "Level1")
                        .WithMany()
                        .HasForeignKey("Level1_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Level3", "Level3")
                        .WithMany("Level4")
                        .HasForeignKey("Level3_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level1");

                    b.Navigation("Level3");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Level1", b =>
                {
                    b.Navigation("Level2");
                });

            modelBuilder.Entity("Domain.Entities.Level2", b =>
                {
                    b.Navigation("Level3");
                });

            modelBuilder.Entity("Domain.Entities.Level3", b =>
                {
                    b.Navigation("Level4");
                });
#pragma warning restore 612, 618
        }
    }
}
